<?php

use Drupal\Core\Routing\RouteMatchInterface;

function as_people_ldap_get_netid_ldap($netid) {

  // get settings
  $config = \Drupal::config("as_people_ldap.settings");
  $settings = [];
  $settings["ldaprdn"] = $config->get("ldaprdn");
  $settings["ldappass"] = $config->get("ldappass");
  // ldap server connection variables
  $ldap_host = 'directory.cornell.edu';
  $ldap_port = '636';
  //set cache id
  $cid = 'as_people_ldap:' . $netid;
  // generate a random number between 4 and 6 days (in seconds) to provide cache life variable
  $clife = rand(345600,518400);
  $info = [];
  //check cache
  if ($cache = \Drupal::cache('data')->get($cid)) {
    //fetch cache data
    $info = $cache->data;
  } else {
    // basic sequence with LDAP is connect, bind, search, interpret search
    // result, close connection
    // using ldap bind
    // Connect to directory.cornell.edu
    $ds = ldap_connect('ldap://directory.cornell.edu');
    //$ds = ldap_connect('ldaps://'. $ldap_host. ':'. $ldap_port);
    ldap_set_option($ds, LDAP_OPT_NETWORK_TIMEOUT, 2); /* 2 second timeout */
    // If connection OK, Bind to server
    if (!empty($ds)) {
      $r = ldap_bind($ds, $settings["ldaprdn"], $settings["ldappass"]);
      $sr = ldap_search($ds,'ou=People,o=Cornell University,c=US','uid='.$netid);
      $info = ldap_get_entries($ds, $sr);
      //$entry = ldap_first_entry($ds, $sr);
    //if (!empty($entry)) {
    if (str_contains($info[0]['cornelledupublishedemail'][0], '@cornell.edu')) {
      // example of how to add data to array if needed
      //$validemail =  array_push($info[0], 'validemail');
      //$info[0]['validemail'] = array('count' => '1',TRUE);
      //set cache
      \Drupal::cache('data')
        ->set($cid, $info, time() + $clife);
      ldap_close($ds);
      }
    } 
  } 

  //dump($info);
return $info;

}



/**
 * Implements hook_help().
 */
function as_people_ldap_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.as_people_ldap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays LDAP people data from directory.cornell.edu by NetID in a block.') . '</p>';

      return $output;
  }
}

